name: soccer_days
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  email_validator: ^1.0.0
  animated_text_kit: ^2.2.0
  flutter_auth_buttons: ^0.10.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
    - assets/ClipartKey_56184.png

